apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: flts
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-11-03T22:32:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: flts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: preprocess
  name: preprocess-g38ze
  namespace: default
  resourceVersion: "1059890"
  uid: 16afc62b-ec23-4e62-aa69-1f2cd03d4a0e
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 16afc62b-ec23-4e62-aa69-1f2cd03d4a0e
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: flts
        app.kubernetes.io/name: preprocess
        batch.kubernetes.io/controller-uid: 16afc62b-ec23-4e62-aa69-1f2cd03d4a0e
        batch.kubernetes.io/job-name: preprocess-g38ze
        controller-uid: 16afc62b-ec23-4e62-aa69-1f2cd03d4a0e
        job-name: preprocess-g38ze
    spec:
      containers:
      - env:
        - name: GATEWAY_URL
          value: http://fastapi-app:8000
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: PRODUCER_TOPIC_0
          value: training-data
        - name: PRODUCER_TOPIC_1
          value: inference-data
        - name: SCALER
          value: MinMaxScaler
        - name: DATASET_NAME
          value: PobleSec
        - name: SAMPLE_TRAIN_ROWS
          value: "50"
        - name: SAMPLE_TEST_ROWS
          value: "50"
        - name: SAMPLE_STRATEGY
          value: head
        - name: SAMPLE_SEED
          value: "42"
        - name: FORCE_REPROCESS
          value: "1"
        - name: EXTRA_HASH_SALT
          value: v2_prophet_fix
        - name: CONFIG_PATH
          value: /app/config.json
        image: preprocess:latest
        imagePullPolicy: IfNotPresent
        name: preprocess
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - |
          until nc -z fastapi-app 8000; do
            echo "Waiting for FastAPI..."
            sleep 2
          done
        image: busybox:1.35
        imagePullPolicy: IfNotPresent
        name: wait-for-fastapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - |
          until nc -z kafka 9092; do
            echo "Waiting for Kafka..."
            sleep 2
          done
        image: busybox:1.35
        imagePullPolicy: IfNotPresent
        name: wait-for-kafka
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  completionTime: "2025-11-03T22:32:47Z"
  conditions:
  - lastProbeTime: "2025-11-03T22:32:47Z"
    lastTransitionTime: "2025-11-03T22:32:47Z"
    message: Reached expected number of succeeded pods
    reason: CompletionsReached
    status: "True"
    type: SuccessCriteriaMet
  - lastProbeTime: "2025-11-03T22:32:47Z"
    lastTransitionTime: "2025-11-03T22:32:47Z"
    message: Reached expected number of succeeded pods
    reason: CompletionsReached
    status: "True"
    type: Complete
  ready: 0
  startTime: "2025-11-03T22:32:31Z"
  succeeded: 1
  terminating: 0
  uncountedTerminatedPods: {}
