---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eval
  labels:
    app: eval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eval
  template:
    metadata:
      labels:
        app: eval
    spec:
      containers:
        - name: eval
          image: eval:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: MODEL_TRAINING_TOPIC
              value: model-training
            - name: MODEL_SELECTED_TOPIC
              value: model-selected
            - name: DLQ_MODEL_SELECTED
              value: DLQ-model-selected
            - name: EVAL_GROUP_ID
              value: eval-promoter
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              value: minioadmin
            - name: AWS_SECRET_ACCESS_KEY
              value: minioadmin
            - name: AWS_S3_ADDRESSING_STYLE
              value: path
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: GATEWAY_URL
              value: http://fastapi-app:8000
            - name: PROMOTION_BUCKET
              value: model-promotion
            - name: LOOKBACK_RUNS
              value: "50"
            - name: IDENTIFIER
              value: default
            - name: EXPECTED_MODEL_TYPES
              value: GRU,LSTM,PROPHET
          ports:
            - containerPort: 8050
              name: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8050
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8050
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eval
  labels:
    app: eval
spec:
  selector:
    app: eval
  ports:
    - name: http
      port: 8050
      targetPort: 8050


