apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inference-slo-scaler
  namespace: default
  labels:
    app: inference
    component: ml-inference
spec:
  scaleTargetRef:
    name: inference
  minReplicaCount: 5  # Production baseline - prevent latency collapse
  maxReplicaCount: 10  # Reduced to prevent node saturation (was 20)
  pollingInterval: 10  # Check metrics every 10 seconds (was 15)
  cooldownPeriod: 180  # Wait 3 minutes before scaling down
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 30  # Faster scale-up (was 60)
          policies:
          - type: Pods
            value: 2  # Add 2 pods per cycle
            periodSeconds: 15  # Every 15 seconds (was 30)
          - type: Percent
            value: 50  # Or 50% of current
            periodSeconds: 15
          selectPolicy: Max
        scaleDown:
          stabilizationWindowSeconds: 300  # Keep 5 minutes (was 180)
          policies:
          - type: Pods
            value: 1  # Remove 1 pod per cycle
            periodSeconds: 60  # Every 60 seconds (was 120)
          - type: Percent
            value: 10  # Or 10% of current (was 25%)
            periodSeconds: 120
          selectPolicy: Min
  triggers:
  # Primary driver: p95 latency > 1.5s (aggressive threshold)
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local:80
      metricName: inference_latency_p95
      query: |
        histogram_quantile(0.95, 
          sum(rate(inference_latency_seconds_bucket[2m])) by (le)
        )
      threshold: "0.8"  # Scale if p95 > 0.8s (800ms) - production tuning
      activationThreshold: "0.4"  # Activate if p95 > 0.4s (400ms) - pre-trigger
  # Secondary driver: queue length > 20 jobs
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local:80
      metricName: inference_queue_length_avg
      query: |
        avg(inference_queue_len)
      threshold: "20"
      activationThreshold: "10"
  # Guardrail: CPU > 85% (prevent saturation)
  - type: cpu
    metricType: Utilization
    metadata:
      value: "85"
  # Guardrail: Memory > 80% (prevent OOM)
  - type: memory
    metricType: Utilization
    metadata:
      value: "80"
