apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inference-guardrail-hpa
  namespace: default
  labels:
    app: inference
    role: guardrail
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inference
  minReplicas: 3
  maxReplicas: 20
  metrics:
  # CPU guardrail - prevent CPU saturation
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
  # Memory guardrail - prevent OOM
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min
