---
# Locust Master Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: default
  labels:
    app: locust
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
      - name: locust
        image: locustio/locust:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOCUST_LOCUSTFILE
          value: "/home/locust/locustfile.py"
        - name: TARGET_HOST
          value: "http://inference:8000"
        command: ["locust"]
        args:
        - "--master"
        - "--master-bind-host=0.0.0.0"
        - "--master-bind-port=5557"
        - "--expect-workers=4"
        - "--host=http://inference:8000"
        - "--loglevel=INFO"
        ports:
        - name: web
          containerPort: 8089
          protocol: TCP
        - name: master-p1
          containerPort: 5557
          protocol: TCP
        - name: master-p2
          containerPort: 5558
          protocol: TCP
        volumeMounts:
        - name: locust-scripts
          mountPath: /home/locust
        - name: results
          mountPath: /results
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8089
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8089
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: locust-scripts
        configMap:
          name: locust-scripts
      - name: results
        emptyDir: {}
---
# Locust Master Service
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: default
  labels:
    app: locust
    role: master
spec:
  type: NodePort
  selector:
    app: locust
    role: master
  ports:
  - name: web
    port: 8089
    targetPort: 8089
    nodePort: 30889  # Accessible at localhost:30889
    protocol: TCP
  - name: master-p1
    port: 5557
    targetPort: 5557
    protocol: TCP
  - name: master-p2
    port: 5558
    targetPort: 5558
    protocol: TCP
