---
apiVersion: v1
kind: ConfigMap
metadata:
  name: preprocess-config
data:
  config.json: |
    {
        "data": {
            "input_bucket": "dataset",
            "train_file": "PobleSec.csv",
            "test_file": "PobleSec_test.csv",
            "output_bucket": "processed-data",
            "output_train": "processed_data",
            "output_test": "test_processed_data"
        },
        "preprocessing": {
            "handle_nans": {
                "enabled": true,
                "threshold": 0.33,
                "knn_neighbors": 2,
                "drop_rows": false
            },
            "outliers": {
                "enabled": false,
                "method": "iqr",
                "factor": 1.5
            },
            "time_features": {
                "enabled": true
            },
            "lags": {
                "enabled": false,
                "n_lags": 0,
                "step": 1
            },
            "scaling": {
                "method": "MinMaxScaler",
                "add_constant": null
            }
        }
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: preprocess
  labels:
    app: preprocess
spec:
  template:
    metadata:
      labels:
        app: preprocess
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - >
              until nc -z kafka 9092; do echo "waiting for kafka"; sleep 3; done;
              until nc -z fastapi-app 8000; do echo "waiting for fastapi"; sleep 3; done;
              until nc -z minio 9000; do echo "waiting for minio"; sleep 3; done;
              echo "dependencies ready";
      containers:
        - name: preprocess
          image: preprocess:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GATEWAY_URL
              value: http://fastapi-app:8000
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: PRODUCER_TOPIC_0
              value: training-data
            - name: PRODUCER_TOPIC_1
              value: inference-data
            - name: CONFIG_PATH
              value: /app/config/config.json
            - name: IDENTIFIER
              value: default
            - name: DATASET_NAME
              value: PobleSec
            - name: SAMPLE_TRAIN_ROWS
              value: "50"
            - name: SAMPLE_TEST_ROWS
              value: "50"
            - name: SAMPLE_STRATEGY
              value: head
            - name: SAMPLE_SEED
              value: "42"
            - name: FORCE_REPROCESS
              value: "1"
            - name: EXTRA_HASH_SALT
              value: ""
          volumeMounts:
            - name: preprocess-config
              mountPath: /app/config
      volumes:
        - name: preprocess-config
          configMap:
            name: preprocess-config


